baseURL = "http://christianfscott.com/"
languageCode = "en-au"
title = "Christian Scott"
googleAnalytics = "UA-106948574-1"
[permalinks]
  posts = "/:title"
[params]
  description = "software engineer in sydney, australia"
[markup]
  [markup.highlight]
    style = "borland"
