baseURL = "https://www.christianfscott.com/"
languageCode = "en-au"
title = "Christian Scott"
googleAnalytics = "UA-106948574-1"
enableRobotsTXT = true
[permalinks]
  blog = "/:filename"
[params]
  description = "software engineer in sydney, australia"
  images = ["logo.png"]
[markup]
  [markup.highlight]
    style = "borland"
