baseURL = "https://christianfscott.com/"
languageCode = "en-au"
title = "Christian Scott"
googleAnalytics = "UA-106948574-1"
[permalinks]
  blog = "/:filename"
[params]
  description = "software engineer in sydney, australia"
[markup]
  [markup.highlight]
    style = "borland"
